version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.12.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 13.1.1
    - 13.1.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
  - dependency-name: node-notifier
    versions:
    - 8.0.2
